### ISSUE TITLE
checklist: Textpattern tag changes

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#118]
A list of behavioural changes in tags that will need documenting (please add additional items if I've missed any):

- [x] `txp:article` tag accepts `breakform` attribute.
- [x] `txp:article_custom` tag accepts `breakform` attribute.
- [x] `txp:output_form` tag accepts `context` and `format` attributes.
- [x] `txp:css` tag accepts additional options for `format` attribute.
- [x] `txp:link_to_next` tag accepts `context` attribute. **4.7.2**
- [x] `txp:link_to_prev` tag accepts `context` attribute.  **4.7.2**
- [x] `txp:page_url` tag accepts `context` attribute. **4.7.2**
- [x] `txp:permlink` tag accepts `context` attribute.
- [x] `txp:if_different` tag accepts `test` attribute.
- [x] Article lists (actual tag(s) TBC) can be split by `breakby` form value.
- [x] Global `escape="ordinal|spell|url"` attribute values.
- [x] Global `trim` and `default` attributes.
- [x] Global `wrapform` attribute.
- [x] `aria_label` and `placeholder` attributes on comment input fields.
- [x] `txp:search_input` can be used as a container tag, and also accepts `aria_label` and `placeholder` attributes.
- [x] `txp:variable` tag accepts `add`, `output`, `reset` and `separator` attributes.
- [x] `txp:section_list` accepts valueless `exclude` attribute so non-searchable sections can be omitted from `txp:section_list` output. **4.8.0**
- [x] `txp:category_list` tag's `sort` attribute now respects `categories` attribute instead of requiring `sort=""` override.
- [ ] `txp:item` tag added. **4.8.0**
- [ ] Added `title` attribute to image tags. **4.8.0**
- [ ] Added `class` attribute to comment form tags. **4.8.0**
- [ ] Added `month` and `time` attributes to `<txp:file_download_list />` and `<txp:linklist>` tags. **4.8.0**
- [ ] Added `pg`, `total` and `limit` attributes to `<txp:newer />` and `<txp:older />` tags. **4.8.0**
- [ ] Custom fields support from/to date filtering. **4.8.0**
- [ ] Support for `id` ranges in some tags and admin fields. **4.8.0**
- [ ] Global `evaluate`, `replace`  and `yield` attributes. **4.8.0**
- [ ] Ability to trim lists when using valueless `trim` attribute. **4.8.0**
- [ ] Added `size` attribute to `<txp:images>` tag to filter by aspect ratio. **4.8.2**

**Comment by philwareham** [comment]
@bloatware I've updated the https://docs.textpattern.com/tags/css with `format` changes and https://docs.textpattern.com/tags/output_form with `context` and `format` changes - can you verify this info is correct, as I'm a little unsure?

**Comment by bloatware** [comment]
Thanks @philwareham, that's fine for `css`, I would just put it more like this for `output_form`:
```
format="image, link, script, url"
```
eventually prepended by `flat.` to fetch the form from disk.

**Comment by philwareham** [comment]
@Bloke @bloatware Can you please give me a bit of info on the `<txp:item />` tag and it's usage? I'll then complete the tag doc for it. Thanks!

**Comment by bloatware** [comment]
@philwareham `<txp:item />` outputs various chunks of information that currently have no their own tag. For example, `<txp:item name="url" />` outputs pagination urls inside `<txp:pages />`. I don't think it's ready for documentation.
