### ISSUE TITLE
Interface strings formatting checklist

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#126]
If the docs are to be checked for updating interface strings against new [formatting standards](https://docs.textpattern.com/brand/user-documentation-guidelines#formatting-interface-strings), a checklist will be useful to keep track of what pages are done. I'd say just do pages as you happen to look at one, then check it off. No mad rush to get them current yesterday. That's how I'm approaching it. As all files in a given folder are completed, remove files from the list and leave the folder checked. (See side topic at bottom of list.)

- [ ] /administration
  - [ ] admin-fast-track.md
  - [ ] articles-panel.md
  - [ ] categories-panel.md
  - [ ] comments-panel.md
  - [ ] diagnostics-panel.md
  - [ ] extensions-region.md
  - [ ] files-panel.md
  - [ ] forms-panel.md
  - [ ] home-region.md
  - [ ] images-panel.md
  - [ ] index.md
  - [ ] languages-panel.md
  - [ ] links-panel.md
  - [ ] pages-panel.md
  - [ ] plugins-panel.md
  - [ ] preferences-panel.md
  - [ ] sections-panel.md
  - [ ] security.md
  - [ ] styles-panel.md
  - [ ] themes-panel.md
  - [ ] user-roles-and-privileges.md
  - [ ] users-panel.md
  - [ ] visitor-logs-panel.md
  - [ ] write-panel.md
- [x] /brand
- [ ] /development
  - [ ] admin-side-events-and-steps.md
  - [ ] admin-side-plugin-tutorial.md
  - [ ] contributing.md
  - [ ] core-callbacks-reference.md
  - [ ] database-schema-reference.md
  - [ ] index.md
  - [ ] plugin-developer-prefixes.md
  - [ ] plugin-template-help.md
  - [ ] plugin-user-help-guidelines.md
  - [ ] plugin-vs-core.md
  - [ ] public-side-plugin-tutorial.md
  - [ ] textpattern-source-code-repositories.md
  - [ ] the-pluggable-ui-function.md
- [ ] /faqs
- [ ] /installation
  - [ ] configuring-a-web-server-for-textpattern.md
  - [ ] content-security-policy.md
  - [ ] index.md
  - [ ] installing-on-an-nginx-webserver.md
  - [ ] installing-textpattern.md
  - [ ] moving-textpattern.md
  - [ ] multi-site-textpattern.md
  - [ ] post-install-and-upgrade-routines.md
  - [ ] troubleshooting-textpattern.md
  - [ ] upgrading-textpattern.md
  - [ ] view-hidden-files-on-macos.md
- [ ] /tags
  - [ ] /shortcodes
    - [ ] aside-quote-shortcode.md
    - [ ] custom-short-tags-and-shortcodes.md
    - [ ] download-link-shortcode.md
    - [ ] image-with-caption-shortcode.md
    - [ ] index.md
    - [ ] video-embed-shortcode.md
  - [ ] /tag-basics
    - [ ] core-short-tags.md
    - [ ] incorrect-tag-contexts.md
    - [ ] index.md
    - [ ] integrated-tag-notation.md
    - [ ] parser-and-passes.md
    - [ ] parsing-tag-attributes.md
    - [ ] self-closed-versus-container-tags.md
    - [ ] tag-escaping.md
    - [ ] tag-nesting.md
- [ ] /themes
    - [ ] admin-side-themes.md
    - [ ] form-templates-explained.md
    - [ ] front-end-themes.md
    - [ ] index.md
    - [ ] naming-conventions-for-template-authors.md
    - [ ] page-templates-explained.md
    - [ ] themes-on-github.md

Would also be a good time to look at file names and think about some standard procedures to name them, with objective to prevent overly long names. That's something needing documented in the collaboration procedures anyway: file naming. 

For example: 

### File naming

In order to keep files consistent, easy to scan in a file tree, and relatively sane in length, use the following convention to name files.

1. Start with title of document by default. If surpasses [n?] characters, do these in order until char limit is okay: 
  1. drop 'textpattern' entirely (needless)
  2. change all 'front-end' to 'frontend' and all 'admin-side' to 'backend' (these are adjectives, and we're collapsing hyphen)
  3. change 'documentation' (plural) to 'docs'
  4. change 'guidelines' to 'guide'
  5. change 'reference' to 'ref'
  6. change 'tutorial' to 'tute'

That should probably be enough. Or make them all standard to begin with? Better for consistency?

Regarding 1.2, I just moved a relevant section in the docs guidelines to the editorial style guide draft about not abbreviating common words, which 'admin' fall into. I know, I know. But it's about being better with style and consistency, and about being clear (is 'administration' or 'administrator'?) And places in the back end actually use interface strings for 'Admin' or 'Admin-side'. The only time anyone should use either abbreviation in documentation, then, is when referring to those specific locations. With that in mind, it suggests maybe some interface string tweaks. How big of deal would it be to use 'Settings' instead of 'Admin' on that main back-end section na/link? And maybe the pref should read 'Back-end theme' (adjective form). Just a few thoughts of more I'll be bugging people about. ;)

**Comment by wion** [comment]
I've revised [/themes/front-end-themes.md](https://docs.textpattern.com/themes/front-end-themes). Whoever last added the informative content to that page should probably have a look at the [Formatting interface strings](https://docs.textpattern.com/brand/user-documentation-guidelines#formatting-interface-strings) guidelines.

**Comment by wion** [comment]
**Notice:**
I have moved the dozens of offline FAQ docs that were clogging up the _/faqs_ directory to _../_recycle/needless-faqs_. If ever needed for whatever reason, we can pluck them from there, but at least they are out of the way.
