### ISSUE TITLE
checklist: ../administration/{name}-panel pages

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#135]
## Situation

A new page, [Common panel functionality](https://docs.textpattern.com/administration/common-panel-functionality), has been created that allows revising the panel documentation pages listed below so that repetitive explanation of these secondary features may be replaced with a mere link to the new page instead. See demonstration of this with the Themes panel ( #130 ), which is being revised as described.

## Purpose of this issue

This issue serves as an overhead reminder of the effort, and makes clear which panel pages are presumably in need of revision.

A new issue should be created (if one does not already exist, open or closed) for each panel page, individually, as an editor takes up the task to revise it. This helps work to establishing the 1:1 relationship of issues to pages for change-history record keeping, as will be detailed in the forthcoming collaboration procedures.

## Checklist

Content:

- [ ] [Articles](https://docs.textpattern.com/administration/articles-panel)
- [ ] [Images](https://docs.textpattern.com/administration/images-panel)
- [ ] [Files](https://docs.textpattern.com/administration/files-panel)
- [ ] [Links](https://docs.textpattern.com/administration/links-panel)
- [ ] [Comments](https://docs.textpattern.com/administration/comments-panel)

Presentation:

- [ ] [Themes](https://docs.textpattern.com/administration/themes-panel) (in progress #130)
- [ ] [Sections](https://docs.textpattern.com/administration/sections-panel)

Admin:

- [ ] [Users](https://docs.textpattern.com/administration/users-panel)
- [ ] [Plugins](https://docs.textpattern.com/administration/plugins-panel)
