### ISSUE TITLE
checklist: Clean up version numbers

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#141]
## Situation

Objective to remove (and avoid future use of) needless version numbers in user docs except as relevant legacy references (such as on tag pages). There's not many, apparently, but if you know of more, please add to list.

## Checklist

Current list of references to 4.x. Only found a handful besides tags:

- [x] [/themes/index.md](https://docs.textpattern.com/themes/index.html)
- [x] [/administration/index.md](https://docs.textpattern.com/administration/index.md)
- [x] [/administration/preferences-panel.md](https://docs.textpattern.com/administration/preferences-panel.md)
- [x] [/brand/user-docs-guide.md](https://docs.textpattern.com/brand/user-docs-guide.md)

**Comment by wion** [comment]
Done. I think. We'll just have to edit any others out as they are found. But I think it's mostly legacy references at this point, which are not a problem.
